### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Flamingo#1]
@zenangst @RamonGilabert @onmyway133 Ok, let's give it one more try. We need a kickass name for our brand new Swift web framework :smiley_cat: 

Have a few suggestions:

1) **Flamingo** - following the bird naming trend for Swift packages.
![tumblr_nhpya2ibnc1s7tor4o1_500](https://cloud.githubusercontent.com/assets/10529867/13380689/18360ae8-de49-11e5-9975-7d9d14de27b1.jpg)

2) **Flamenco** - without any hidden meanings, just similar to the previous one.
![27279_original](https://cloud.githubusercontent.com/assets/10529867/13380692/2223679e-de49-11e5-9713-f022d6b44954.jpg)

3) **Aurora** - kinda like this one, but there is a framework from Apache with the same name, it's not in Swift ofc, but could affect recognition: https://github.com/apache/aurora

So yeah, just throw your ideas here :smiley:

**Comment by RamonGilabert** [comment]
Oh dude... The first one would give for the biggest of the logos. I'll think about a name.

**Comment by zenangst** [comment]
I like **Flamingo** :grin: 

It could be called **Apodidae**.

> The swifts are a family, Apodidae, of highly aerial birds.

**Comment by vadymmarkov** [comment]
@zenangst Like the idea behind **Apodidae**, but I think it's too hard to remember :smile: Checked the list of swift birds and found **Cypsiurus**, sounds nice for me, but still, kinda specific.

**Comment by RamonGilabert** [comment]
Scientific names. Are you serious?

**Comment by zenangst** [comment]
I agree, latin names are kinda hard to remember and to pronounce, so far Flamingo is my favourite :sunglasses:

**Comment by onmyway133** [comment]
Some bird lists like this maybe source of inspiration https://en.wikipedia.org/wiki/List_of_birds_by_flight_speed :bird: 

But Flamingo sounds good to me

**Comment by vadymmarkov** [comment]
OK, if everyone likes Flamingo, let's close this issue and rename the repo?

**Comment by sindrenm** [comment]
Yeah!

**Comment by vadymmarkov** [comment]
Even @sindrenm agrees. You guys @zenangst @RamonGilabert @onmyway133 are just ignoring me :disappointed:

**Comment by zenangst** [comment]
wat, I said yay-isch.

> I like **Flamingo** :grin:

**Comment by vadymmarkov** [comment]
yay-isch :grin:

**Comment by RamonGilabert** [comment]
It's ait.

**Comment by sindrenm** [comment]
Should I close and rename?

**Comment by RamonGilabert** [comment]
This is the definition of free time basically.

**Comment by sindrenm** [comment]
This is the definition of wanting to stop getting notifications from this issue. :wink:

**Comment by RamonGilabert** [comment]
You can unsubscribe though!

**Comment by sindrenm** [comment]
But I want the best for you folks! And that would be to fix up the name. :grinning:

**Comment by vadymmarkov** [comment]
:boom: It happened https://github.com/hyperoslo/Flamingo

**Comment by vadymmarkov** [comment]
If you have some ideas with other kickass name, feel free to create new issue :wink: And special thanks to @sindrenm who accelerated the process :smile:

**Comment by zenangst** [comment]
@sindrenm :heart:

**Comment by sindrenm** [comment]
Awesome, guys! :grinning:

**Comment by RamonGilabert** [comment]
Flam.

![mg_7684](https://cloud.githubusercontent.com/assets/6138120/16008092/75c7362a-3176-11e6-89ee-245b5ef54e23.jpg)

**Comment by RamonGilabert** [comment]
Yo @hyperoslo/ios we have a name:

Horisont.

**Comment by vadymmarkov** [comment]
Mar

**Comment by vadymmarkov** [comment]
Doorz, "z" is important to keep it unique 😄

**Comment by vadymmarkov** [comment]
Neonix, Neonic.

**Comment by sindrenm** [comment]
Horisont WTF‽

**Comment by RamonGilabert** [comment]
I don't think we are going to go for that really, you've used it in some other place.

**Comment by zenangst** [comment]
Neonic has a nice ring to it I think. We could make 80's inspired cover for it ;)
