### ISSUE TITLE
swift build command not found

### ISSUE THREAD

**Issue by onmyway133** [hyperoslo/Flamingo#26]
I was using https://github.com/kylef/swiftenv as in the README, however running `swift build` says command not found and it still points to system toolchain (2.2), although `swiftenv version` shows `
DEVELOPMENT-SNAPSHOT-2016-05-03-a`

Turn out that restarting iTerm fixes the problem 🎉 

Should we state this in the README?

**Comment by vadymmarkov** [comment]
@onmyway133 I think it's more related to https://github.com/kylef/swiftenv setup.

**Comment by onmyway133** [comment]
I think I'll close this. Hope somebody will find this issue 😬
