### ISSUE TITLE
Should we update development snapshot?

### ISSUE THREAD

**Issue by onmyway133** [hyperoslo/Flamingo#27]
For now `https://github.com/hyperoslo/Flamingo/blob/master/.swift-version` is on May 3rd. Should we go with the latest https://swift.org/download/#snapshots, like June 6th for now 😁

**Comment by vadymmarkov** [comment]
@onmyway133 I've started on a branch with the latest Swift snapshot and have to fix dependencies, the same as https://github.com/hyperoslo/Flamingo/issues/28. Will let you know when I get it working.
